language: r

sudo: required

r_github_packages:
  - jimhester/robustr
  - jimhester/covr

before_script:
  - Rscript -e "library(stringi);stri_install_icudt()"

after_success:
  - Rscript -e 'library(covr); coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change

